server_name: test server
log_level: TRACE
thread_limit: -1
cache_path: /data/cache

middle_end:
  ha_mqtt:
    enable: true
    broker_address: 100.113.142.37
    broker_port: 1883
    username: username
    password: password
    broker_keepalive: 60
    sources:
      - cam01
      - cam02

analizers:
  detection:
    type: yolov9-m
    classes:
      - person
      - car
      - motorcycle
      - bus
      - truck
      - cat
      - dog
    min_confidence: 60
    nms: 45
  trigger:
    type: trigger_if_true
  trigger_delay:
    type: bool_delay
    charge_delay: 1
    discharge_delay: 60
  video_recorder:
    type: video_recorder
    format: H264
    extension: mkv
    fps: 1
    storage_path: records
    stop_release: true
  show_debug:
    type: show_image

chains:
  process_debug:
    0:
      detection:
        image: $input.image
    1:
      trigger_delay:
        input: $0.detection.detected
    2:
      trigger:
        input: $1.trigger_delay.output
      video_recorder:
        image: $0.detection.debug_image
        prefix: $input.source_name
        enable: $1.trigger_delay.output
      show_debug:
        image: $0.detection.debug_image
        name: $input.source_name
  process:
    0:
      detection:
        image: $input.image
    1:
      trigger_delay:
        input: $0.detection.detected
    2:
      trigger:
        input: $1.trigger_delay.output
      video_recorder:
        image: $0.detection.debug_image
        prefix: $input.source_name
        enable: $1.trigger_delay.output

sources_settings:
  sources:
    cam01:
      type: url
      url: rtsp://192.168.1.20:554/stream1
      is_live: true
      active_fps: 15
      passive_fps: 1
      process:
        - process_debug
    cam02:
      type: url
      url: rtsp://192.168.1.21:554/stream1
      is_live: true
      active_fps: 15
      passive_fps: 1
      process:
        - process
